# Generated by Django 3.1.4 on 2022-04-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_alter_request_is_ajax'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
    ]
